img_path: "/nfs/turbo/umms-indikar/shared/projects/live_cell_imaging/test/mitosis_example/3x3-extract-Scene6-07-14to15.czi/"
output: "/tmpssd/outputs/"
channels:
    green: 1
    blue: 3
    red: 2
    oblique: 4
threads: 36